image: jagregory/pandoc

pages:
  stage: deploy
  script:
  - pandoc -t revealjs -s -o slides.html presentation.md -V revealjs-url=https://revealjs.com --css=custom.css --slide-level=2 --self-contained
  artifacts:
    paths:
    - slides.html
  only:
  - master
